export const questions = {
  communication: {
    0: "Looks at other people's faces when they are talking to him",
    1: "Looks up or smiles when someone says his name.",
    2: "Laughs when a parent or other person laughs.",
    3: "Raises and lowers voice to express different feelings or needs.",
    4: "Says the names of other people (for example, 'Mama', 'Daddy' or names of friends).",
    5: "Follows simple commands (for example, 'No' or 'Come here').",
    6: "Uses one or more words to get something he wants, even if the word is not said correctly or pronounced well.",
    7: "Shakes head or says 'Yes' or 'No' in response to a simple question (for example, 'Do you want something to drink?').",
    8: "Points to common items in a room when asked (for example, 'Show me the TV').",
    9: "Repeats words others say (for example, says 'baby' when an adult says 'baby').",
    10: "Says phrases with at least two words (for example, 'My book').",
    11: "Says the name of an object clearly enough that others recognize it (for example, 'ball','dog', 'cup').",
    12: "Listens closely for at least 1 minute when people talk.",
    13: "Speaks clearly enough that others who do not know him can understand most of what is said.",
    14: "Follows simple, one-step directions that include 'over' or 'under' (for example, 'Put your hands over your head').",
    15: "Refrains from repeating what he says over and over again.",
    16: "Names 20 or more familiar objects.",
    17: "Sings all or part of the words to songs.",
    18: "Makes plurals of words by adding an -s (for example, 'shoes', 'socks', 'dogs').",
    19: "Uses sentences with a noun and verb.",
    20: "Tells parent, friends, or others about his favorite activities.",
    21: "Asks questions such as 'Will you play with me?'",
    22: "Speaks in sentences of six or more words.",
    23: "Uses past tense to talk about prior events (for example, 'I stayed inside').",
    24: "Has a conversation with another person for at least 3 minutes.",
    25: "Waits for others to finish what they are saying, without interrupting.",
  },
  community: {
    0: "Stays with parents or other family members in a store and does not wander off.",
    1: "Recognizes own home in his immediate neighborhood.",
    2: "Walks on sidewalk rather than street.",
    3: "Informs parents when someone comes to the door.",
    4: "Shows respect for public property (for example, throws trash in cans, does not damage property).",
    5: "Obeys an adult's request to not touch items when shopping.",
    6: "Asks to go to a park or other favorite community place.",
    7: "Knocks on a door or rings the doorbell before entering another person's home.",
    8: "Refrains from talking loudly in a public place (for example, in a theater, movie, or church).",
    9: "Remains seated during a religious service or a movie.",
    10: "Asks to eat in a favorite restaurant.",
    11: "Recognizes and names buildings (for example, hospital, gas station, fire department).",
    12: "Identifies neighborhood locations where his family obtains needed items (for example, where to buy food).",
    13: "Recognizes the need to pay for an item before leaving a store.",
    14: "Describes the duties of workers (for example, says that fire fighters put out fires and doctors help the sick).",
    15: "Looks both ways before crossing a street or parking lot.",
    16: "Asks to go to the library.",
    17: "Finds the restroom in public places.",
    18: "Orders own meals when eating out.",
    19: "Makes a small purchase at a food store.",
    20: "Carries enough money to make small purchases (for example, a soft drink).",
    21: "Walks alone to friends' houses or apartments in the neighborhood.",
  },
  functional: {
    0: "Points to at least one body part when asked (for example, 'head' or 'leg').",
    1: "Turns book pages one by one.",
    2: "Points to pictures in books when asked (for example, points to a horse or cow).",
    3: "Counts three or more objects.",
    4: "States his age in years when asked.",
    5: "Sings the alphabet song.",
    6: "Names six or more colors, including red, blue, and yellow.",
    7: "Names four or more shapes (for example, circle, square, rectangle, triangle).",
    8: "Recites nursery rhymes from memory.",
    9: "Reads his name when printed.",
    10: "Names at least two letters when shown his name.",
    11: "Identifies at least one coin by name (for example, penny or dime).",
    12: "Answers simple questions about a story read to him.",
    13: "Counts 10 or more objects without using fingers.",
    14: "Draws a recognizable face that includes two eyes, a nose, a mouth, and hair.",
    15: "Names most letters when shown the alphabet.",
    16: "Counts from 1 to 20.",
    17: "Prints at least two letters in his name.",
    18: "Reads and obeys common signs (for example, Do Not Enter, Exit, Stop).",
    19: "States the days of the week in order.",
    20: "Writes or prints his first and last name.",
    21: "Writes numbers 1 through 10 correctly.",
    22: "Tells which day comes before another (for example, 'Wednesday comes before Thursday').",
    23: "States days and times of favorite after-school activities, such as sports practice, music lessons, or television shows.",
  },
  homeLiving: {
    0: "Removes cookies, chips, or other food from a box or bag.",
    1: "Shows concern when he spills something (for example, says `Oh no` or tells an adult).",
    2: "Points to where commonly used foods are kept in his home (for example, the refrigerator).",
    3: "Points to the place where his clothes are stored.",
    4: "Takes a shirt or other piece of clothing out of a drawer when asked.",
    5: "Assists other people with putting away toys, games, and other items.",
    6: "Picks up and throws away trash or paper at home.",
    7: "Does a simple errand when asked (for example, runs to get a towel for a spill).",
    8: "Refrains from kicking or hitting furniture.",
    9: "Turns television on and off.",
    10: "Refrains from throwing food or paper on the floor.",
    11: "Washes hands without splashing water on the floor.",
    12: "Gets own snacks from cabinet or pantry.",
    13: "Assists adults with preparing simple snacks or meals (for example, hands slices of bread to adult for making sandwiches).",
    14: "Places dirty clothes in the proper place (for example, a hamper or clothes basket).",
    15: "Wipes up spills at home.",
    16: "Takes own clothes from drawers or closet when getting dressed.",
    17: "Keeps dirty shoes and feet off furniture.",
    18: "Puts his own dirty glass or plate in the sink or dishwasher.",
    19: "Puts things in their proper places when finished using them.",
    20: "Keeps toys, games, and other belongings neat and clean.",
    21: "Disposes of his leftover food.",
    22: "Pours liquid from a larger container into own cup or glass without spilling.",
    23: "Makes his bed.",
    24: "Folds clean clothes.",
  },
  healthAndSafety: {
    0: "Swallows liquid medicines as needed, without fussing.",
    1: "Sits still in high chair, booster seat, or chair, without climbing or sliding off.",
    2: "Avoids bumping into walls or objects when crawling or walking.",
    3: "Allows temperature to be taken without fussing.",
    4: "Shows, points to, or tells another person about a cut, bruise, or other minor injury.",
    5: "Follows another person's direction to 'stop' when near danger, such as fire or broken glass.",
    6: "Points to the body part that hurts when he is sick or injured.",
    7: "Remains fairly still when an adult treats a cut or scrape.",
    8: "Refrains from putting non-edible objects in mouth (for example, crayons, blocks, sand).",
    9: "Avoids getting too near a fire, broken glass, or other potential danger.",
    10: "Avoids touching or playing with dangerous items (for example, insect spray or sharp knives).",
    11: "Avoids crawling or climbing on high or dangerous places.",
    12: "Tells an adult if he has a stomachache or other illness.",
    13: "Tests hot foods before eating them.",
    14: "Puts on a coat or sweater when cold.",
    15: "Carries breakable objects safely and carefully.",
    16: "Asks an adult before going near something that might be dangerous (for example, animals, busy streets, or high playground equipment).",
    17: "Buckles own car seat or seat belt.",
    18: "Carries scissors safely.",
    19: "Carries hot containers safely and carefully.",
    20: "Uses electrical outlets or sockets safely.",
    21: "Cares for own minor injuries (for example, paper cuts, knee scrapes, nosebleeds).",
  },
  leisure: {
    0: "Smiles or shows interest when he sees a favorite toy.",
    1: "Plays with a variety of toys instead of only one or two.",
    2: "Plays with a single toy or game for at least a minute.",
    3: "Plays alone with toys and games, or does other fun activities.",
    4: "Plays simple games like 'peek-a-boo' or rolls a ball to others.",
    5: "Looks with an adult at pictures in books or magazines.",
    6: "Watches for a few minutes as people play with toys or games.",
    7: "Shows interest in a toy or other object by pointing to it.",
    8: "Chooses a game or toy during playtime.",
    9: "Plays with toys, games, or other fun items with others.",
    10: "Plays with a single toy or game for more than 5 minutes.",
    11: "Plays on playground equipment.",
    12: "Asks to be read to from a favorite book.",
    13: "Attends fun activities at another's home.",
    14: "Engages in imaginary or make-believe play with others.",
    15: "Participates regularly in a specific fun activity (for example, listening to a certain type of music or playing a favorite computer game).",
    16: "Plays simple games with playmates without adult supervision.",
    17: "Invites others to join him in playing games and other fun activities.",
    18: "Saves things of interest (for example, rocks, feathers, pictures).",
    19: "Waits for his turn in games and other fun activities.",
    20: "Follows the rules in games and other fun activities.",
    21: "Invites others home for a fun activity.",
    22: "Plays simple board games.",
    23: "Participates in an organized program for a sport or hobby (for example, practices basketball or takes a music class).",
  },
  selfCare: {
    0: "Swallows liquids without difficulty.",
    1: "Sleeps through most of the night, waking no more than one or two times.",
    2: "Swallows soft, strained, or mashed food such as baby food or applesauce.",
    3: "Opens mouth when offered food on a spoon.",
    4: "Feeds himself crackers, cookies, dry cereal, or other finger foods.",
    5: "Eats firm foods that require biting and chewing (for example, steamed vegetables).",
    6: "Drinks from a cup or glass, even if another person must hold it.",
    7: "Lifts arms as needed when another person is dressing or undressing him or her.",
    8: "Points to or asks for food when hungry.",
    9: "Takes shoes off.",
    10: "Feeds himself with a spoon or fork, not hands.",
    11: "Washes hands with both soap and water.",
    12: "Wipes his face when given a washcloth by an adult.",
    13: "Remains dry without wetting throughout the day.",
    14: "Sits on the toilet or potty seat without being held.",
    15: "Tells parent or other adult when he needs to use the bathroom.",
    16: "Remains dry without wetting throughout the night.",
    17: "Brushes teeth with little fussing when told to do so by an adult.",
    18: "Uses bathroom without help.",
    19: "Dresses himself.",
    20: "Buttons own clothing.",
    21: "Takes a bath or shower without help.",
    22: "Washes his own hair.",
    23: "Cuts meats or other foods into bite-size pieces with a knife.",
  },
  selfDirection: {
    0: "Shows interest in a toy or other object by looking at it for a few seconds.",
    1: "Sits quietly for at least 1 minute without demanding attention.",
    2: "Finds something to do for at least 5 minutes without demanding attention.",
    3: "Plays with a toy without putting it into his mouth.",
    4: "Explores an unfamiliar room or other new situation, even if a parent must encourage it (for example, a doctor's waiting room).",
    5: "Chooses the food or snack he wishes to eat when given a choice.",
    6: "Moves a few feet away from a parent in a new situation as long as the parent is in sight (for example, when visiting an unfamiliar residence).",
    7: "Tries to do most things alone without an adult's help (for example, dressing or feeding self).",
    8: "Follows an adult's request to quiet down or behave.",
    9: "Resists pushing or hitting another child when angry or upset.",
    10: "Follows simple household rules (for example, 'No running in the house').",
    11: "Stands still when needed, without fidgeting or moving around.",
    12: "Starts an activity at once when told to do so (for example, `Go take a bath').",
    13: "Controls temper when a parent or other adult takes a toy or object away.",
    14: "Asks permission from an adult when needed (for example, 'May I go outside to play?').",
    15: "Keeps working on hard tasks without becoming discouraged, quitting, or needing reminders.",
    16: "Works independently and asks for help only when necessary.",
    17: "Stops a fun activity, without complaining, when told that time is up.",
    18: "Controls temper when disagreeing with friends.",
    19: "Follows a routine without being reminded (for example, brushing teeth before bedtime or feeding a pet).",
    20: "Asks permission before playing with another child's toy or game.",
    21: "Chooses own clothes almost every day.",
    22: "Works on one home or school activity for at least 15 minutes without reminders.",
    23: "Discusses ways to solve conflicts with others (for example, 'You can have this now if I can have it later').",
  },
  social: {
    0: "Smiles when he sees a parent.",
    1: "Relaxes body when held (for example, snuggles).",
    2: "Squeals or laughs when happy or delighted.",
    3: "Displays closeness to a parent (for example, is happy when parent returns).",
    4: "Shows a sense of humor (for example, laughs when someone acts silly).",
    5: "Lifts arms to express a desire to be picked up.",
    6: "Responds differently to familiar and unfamiliar persons (for example, is less warm to an unfamiliar person).",
    7: "Hugs and kisses parents or others.",
    8: "Imitates actions of adults (for example, pretends to clean house or drive a car).",
    9: "Shows respect for persons in authority by following their rules and directions (for example, parents, teachers, police officers).",
    10: "Shares toys willingly with others.",
    11: "Greets other children (for example, says 'Hi').",
    12: "Says 'Thank you' when given a gift.",
    13: "Shows sympathy for others when they are sad or upset.",
    14: "Seeks friendship with others in his age group.",
    15: "Responds appropriately when introduced to others (for example, says 'Hello').",
    16: "Says 'Please' when asking for something.",
    17: "Says when he feels happy, sad, scared, or angry.",
    18: "Displays good table manners (for example, by using a napkin and remaining at the table until excused).",
    19: "Offers assistance to others (for example, to carry packages or put away food).",
    20: "Apologizes if he hurts the feelings of others.",
    21: "Places reasonable demands on friends (for example, does not become upset when a friend plays with another friend).",
    22: "Refrains from saying or doing things that might embarrass or hurt others.",
    23: "Personally makes or buys gifts for family members on birthdays or major holidays.",
  },
  motor: {
    0: "Lifts head to look around.",
    1: "Follows a moving object by turning head.",
    2: "Rolls from stomach to side.",
    3: "Shakes rattle or other toys.",
    4: "Reaches for objects such as a bottle or toy.",
    5: "Transfers objects from one hand to the other.",
    6: "Sits upright on the floor without support.",
    7: "Moves to a sitting position, even if balance is unsteady.",
    8: "Pulls himself to a standing position (for example, in a crib).",
    9: "Picks up small flat objects from a table (for example, coins or buttons).",
    10: "Crawls for about 10 feet without falling over.",
    11: "When standing, bends over to pick up items from the floor.",
    12: "Stands up from a sitting position.",
    13: "Rolls ball to others.",
    14: "Walks without help.",
    15: "Throws a small ball overhand.",
    16: "Walks up at least five to six steps without falling (may use handrail).",
    17: "Kicks a ball without falling.",
    18: "Runs without falling.",
    19: "Bounces a ball for several seconds.",
    20: "Catches a ball tossed from 5 to 10 feet away.",
    21: "Draws straight lines across a piece of paper.",
    22: "Colors within the lines of a drawing or in a coloring book.",
    23: "Puts twist-off tops back on jars and closes them tightly.",
    24: "Uses scissors to cut along a straight line.",
    25: "Uses scissors to cut shapes with curved lines.",
  },
};

const retrieveQuestions = (type, index) => {
  if (questions[type] && questions[type][index]) {
    return questions[type][index];
  }
  return null;
};

export default retrieveQuestions;
